backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\QuickEmail;
use common\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{

    const PAGE_SIZE = 25;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'upload-image-ckeditor', 'profile'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'upload-image-ckeditor' => [
                'class' => 'backend\components\UploadImageCkEditor',
                'path' => dirname(dirname(__DIR__)) . '/frontend/web/userfiles/ckeditor_upload/'
            ]
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $email = new QuickEmail();
        if(Yii::$app->request->post()){
            $this->_sendEmail($email);
        }
        return $this->render('index', [
            'email' => $email,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $this->layout = false;
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string
     * @throws \Exception
     */
    public function actionProfile()
    {
        $model = User::findOne(['id' => 1]);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->update();
            Yii::$app->session->setFlash('success', 'Сохранено успешно');
        }

        return $this->render('profile', [
            'model' => $model
        ]);
    }

    /**
     * @param $email
     */
    private function _sendEmail($email)
    {
        if ($email->load(Yii::$app->request->post()) && $email->validate()) {
            $email->sendEmail(Yii::$app->user->identity->email);
            Yii::$app->session->setFlash('success', 'Сообщение отправлено!');
        } else {
            Yii::$app->session->setFlash('success', 'Возникла ошибка при отправке сообщения:(');
        }
    }

    /*
     |-----------------------------------------------------------
     |   PROTECTED_FUNCTIONS
     |-----------------------------------------------------------
     */

    /**
     * @param $query
     * @return ActiveDataProvider
     * @throws NotFoundHttpException
     */
    protected function findData($query)
    {
        $model = new ActiveDataProvider([
            'query' => $query,
            'sort' => false,
            'pagination' => new Pagination([
                'pageSize' => self::PAGE_SIZE,
                'forcePageParam' => false,
                'pageSizeParam' => false
            ])
        ]);

        if(!$model){
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        return $model;
    }

    /**
     * @param $model
     * @return \yii\web\Response
     */
    protected function loadData($model)
    {
        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            return (isset($model->parent_id) && $model->parent_id)
                ? $this->redirect(Yii::$app->homeUrl.$this->module->id .'/items/'.$model->parent_id)
                : $this->redirect(Yii::$app->homeUrl.$this->module->id);
        }
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Catalog;
use common\models\CatalogItems;
use common\models\GalleryImages;
use common\models\Geography;
use common\models\GeographyImages;
use common\models\Lk;
use common\models\NativeEmail;
use common\models\Orders;
use common\models\OrderSend;
use common\models\Subscribers;
use frontend\models\BackCallForm;
use frontend\models\SearchModel;
use Yii;
use yii\web\Controller;
use common\models\Pages;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{

    const ROOT_PATH = 'index';

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'geocode-tool'  => ['post'],
                    'subscribe'     => ['post'],
                    'send-order'    => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
            $this->enableCsrfValidation = false;

        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'geocode-tool' => [
                'class' => 'frontend\components\YandexMapApi',
            ]
        ];
    }

    public function actionIndex()
    {

        $catalogs = CatalogItems::getHits();
        $slider = GalleryImages::getSlider();
        $items = Catalog::getOurProducts();
        return $this->render('index', [
            'model' => $this->_queryOrException(Pages::findOne(['alias' => self::ROOT_PATH, 'publish' => Pages::PUBLISH])),
            'catalogs' => $catalogs,
            'slider' => $slider,
            'items' => $items
        ]);
    }

    public function actionPage($alias)
    {
        $model = $this->_queryOrException(Pages::findOne(['alias' => $alias, 'publish' => Pages::PUBLISH]));
        if($model['template'] == 'get_price'){
             return $this->render($model['template'], [
             'model' => $model,
             $this->layout = 'price'
        ]);
        }else{
                 return $this->render($model['template'], [
            'model' => $model
        ]);   
        }

    }

    public function actionSubscribe()
    {
        $model = new Subscribers();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->sendEmail(Yii::$app->params['adminEmail']);
            Yii::$app->session->setFlash('message', 'Подписка офрилена!');
            $model->save();
        } else {
            Yii::$app->session->setFlash('message', 'Error!');
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionSend()
    {
        $model = new Orders();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->sendEmail(Yii::$app->params['adminEmail']);
            $model->status = 0;
            $model->save();
            Yii::$app->session->setFlash('message', 'Спасибо');
        } else {
            Yii::$app->session->setFlash('message', 'Error!');
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionBackcall()
    {
        $model = new BackCallForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->sendEmail(Yii::$app->params['adminEmail']);
            Yii::$app->session->setFlash('message', 'Спасибо! МЫ с Вами свяжемся в ближайшее время!');
        } else {
            Yii::$app->session->setFlash('message', 'Error!');
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionShopadd()
    {
        $model = new Geography();
        $modelImages = new GeographyImages();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            $modelImages->files = UploadedFile::getInstances($modelImages, 'files');
            $modelImages->upload($model->id);
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionSearch($alias = 'search')
    {
        $searchModel = new SearchModel();
        if(Yii::$app->request->isPost){
            $dataProvider = $searchModel->search(Yii::$app->request->post());
        }
        $model = $this->_queryOrException(Pages::findOne(['alias' => $alias, 'publish' => Pages::PUBLISH]));
        return $this->render($model['template'], [
            'model' => $model,
            'data'  => isset($dataProvider) ? $dataProvider : false
        ]);
    }

    /**
     * @return bool
     */
    public function actionSendOrder()
    {
        $model = new OrderSend();
        $model->name  = Yii::$app->request->post('name');
        $model->email = Yii::$app->request->post('email');
        $model->phone = Yii::$app->request->post('phone');
        if($model->validate()){
            return $model->send();
        }
        return false;
    }

    public function actionAddUserLk(){
        $response['is_new'] = Lk::addUserLk($_POST['email'], isset($_POST['phone'])?$_POST['phone']:'', $_POST['url']);
        return json_encode($response);
    }

    public function actionUserTokenLogin(){
        if($_GET['token']){
            $model = new Lk();
            $user = $model->find()->where(['active_alias' => $_GET['token']])->one();
            if($user){
                $session = Yii::$app->session;
                $session->set('id', $user->id);
                if($_GET['url']){
                    header('Location: '.$_GET["url"].'');
                    die();
                }
                header('Location: /price');
                die();
            }else{
                die('Токена не существует'); // TODO Продумать красивые обработчики
            }
        }else{
            die('Токена не существует'); // TODO Продумать красивые обработчики
        }
    }

    public function actionUserLogout(){
        $session = Yii::$app->session;
        $session->remove('id');
    }

    private function _queryOrException($model)
    {
        if(!$model){
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        return $model;
    }

    /**
     *
     * @return string
     *
     */
    public function actionAskPrice()
    {
        $mail = new NativeEmail();
        $mail->setEmail($_POST['email']);
        $mail->setPhone($_POST['phone']);

        if ($mail->sendNativeEmail()) {
            $response['msg'] = 'Ваше сообщение отправлено';
        } else {
            $response['msg'] = 'Произошла ошибка. Попробуйте еще раз';
        }

        return(json_encode($response));
    }
}

frontend/views/site/_item_search_view.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\helpers\StringHelper;
?>

<a href="<?= \yii\helpers\Url::toRoute([$model['sub_link'].'/view', 'alias' => $model['alias']])?>"><?= Html::encode($model['name'])?></a>
<span><?= Yii::$app->request->getHostInfo()?><?= \yii\helpers\Url::toRoute([$model['sub_link'].'/view', 'alias' => $model['alias']])?></span>
<?= HtmlPurifier::process(StringHelper::truncateWords(str_replace('[image]', '', $model['text']), 25))?>

frontend/views/site/about.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use common\models\Workers;

/* @var $this yii\web\View */
/* @var $model common\models\Pages */
$this->title = Html::encode($model->title);
$this->registerMetaTag([
    'name' => 'description',
    'content' => Html::encode($model->description),
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => Html::encode($model->keywords)
]);
?>

<section class="b1 top-section" style="background-image: url('<?= Yii::getAlias('@boxes') .'/'. $model->boxes['we_produce']['image']?>')">
    <div id="video">
        <div class="video-logo"></div>
        <a class="close"></a>
        <video id="video-frame" autostart loop>
            <source src="/video/tea.mp4" type="video/mp4; codecs="avc1.42E01E, mp4a.40.2""><source src="/video/tea.webm" type="video/webm"><source src="/video/tea.ogv" type="video/ogg">
        </video>
    </div>
    <div class="title">
        <?= $model->name?>
        <?php //= $model->boxes['we_produce']['title']?>
        <?php //= Html::a('<i class="fi fi-menu_about"></i>ПОДРОБНО О КОМПАНИИ', Url::to($model->boxes['we_produce']['link']),['class' => 'btn'])?>
        <a class="play-video"><i class="fi fi-play"></i></a>
    </div>
</section>
<section class="about">
    <!--<div class="top-block b-top-section top-section">
        <div class="title">
            <?//= $model->name?>
        </div>
    </div>-->
    <div class="b-content">
        <div class="inner">
            <?= $model->text?>
            <?php if(isset($model->boxes['ingredients'])):?>
            <div class="b-local">
                <div class="title">
                    <?= $model->boxes['ingredients']['title']?>
                </div>
                    <?= $model->boxes['ingredients']['text']?>
            </div>
            <?php endif;?>
            <?php if(isset($model->boxes['recipes'])):?>
            <div class="b-local">
                <div class="title">
                    <?= $model->boxes['recipes']['title']?>
                </div>
                    <?= $model->boxes['recipes']['text']?>
            </div>
            <?php endif;?>
            <?php if(isset($model->boxes['production'])):?>
            <div class="b-local">
                <div class="title">
                    <?= $model->boxes['production']['title']?>
                </div>
                    <?= $model->boxes['production']['text']?>
            </div>
            <?php endif;?>
        </div>
    </div>
    <div class="b-content-promo screen">
        <div class="inner">
            <ul>
                <li>
                    Партнёры более
                    <div class="circle">
                        1000
                    </div>
                    магазинов
                </li>
                <li>
                    Используем
                    <div class="circle">
                        500<span>тонн</span>
                    </div>
                    сырья в год
                </li>
                <li>
                    Ассортимент
                    <div class="circle">
                        60
                    </div>
                    видов чая
                </li>
            </ul>
        </div>
    </div>
    <div class="b-content-promo mobile">
        <div class="inner">
            <ul class="list-promo">
                <li>
                    Партнёры более
                    <div class="circle">
                        1000
                    </div>
                    магазинов
                </li>
                <li>
                    Используем
                    <div class="circle">
                        500<span>тонн</span>
                    </div>
                    сырья в год
                </li>
                <li>
                    Ассортимент
                    <div class="circle">
                        60
                    </div>
                    видов чая
                </li>
            </ul>
        </div>
    </div>
    <div class="b-content clients">
        <div class="inner">
            <?php if(isset($model->boxes['our_clients'])):?>
            <div class="b-local">
                <div class="title">
                    <?= $model->boxes['our_clients']['title']?>
                </div>
                    <?= $model->boxes['our_clients']['text']?>
            </div>
            <?php endif;?>
            <div class="logos">
                <?= Html::ul(\common\models\Ourclients::getList(), ['item' => function($item) {
                    return Html::tag(
                        'li',
                        Html::img('@ourclients/'.$item['image'])
                    );
                }])?>
            </div>
        </div>
    </div>
    <?php if(isset($model->boxes['geography_points'])):?>
    <div class="geography-sale">
        <div class="inner center">
            <div class="text">
                <?= $model->boxes['geography_points']['title']?>
            </div>
            <?= Html::a('НАЙТИ', Url::to($model->boxes['geography_points']['link']),['class' => 'btn green'])?>
        </div>
    </div>
    <?php endif;?>
    <div class="b-content employees">
        <div class="inner">
            <div class="b-local">
                <div class="title">
                    Сертификаты
                </div>
            </div>
            <?= Html::ul(Workers::getList(), ['item' => function($item, $index) {
                $image = Html::a(Html::img('@workers' .'/'. $item['image']), Url::to('@workers' .'/'. $item['image']), ['class' => 'fancybox']);
                return Html::tag(
                    'li',
                    Html::tag('div', $image, [ 'class' => 'img']) . Html::tag('p',$item['name'] . Html::tag('span', $item['appointment']))
                );
            }]) ?>
            <?php if(isset($model->boxes['vacancy'])):?>
            <div class="b-local vacations">
                <div class="title fleft">
                    <?= $model->boxes['vacancy']['title']?>
                </div>
                    <?= $model->boxes['vacancy']['text']?>
                <?= Html::a('ВАКАНСИИ', Url::to($model->boxes['vacancy']['link']),['class' => 'btn green'])?>
            </div>
            <?php endif;?>
        </div>
    </div>
</section>

frontend/views/site/blog.php
<?php

use yii\helpers\Html;
use common\models\Blog;
use yii\helpers\Url;
use common\models\Subscribers;
use yii\helpers\StringHelper;

/* @var $this yii\web\View */
/* @var $model common\models\Pages */
$this->title = Html::encode($model->title);
$this->registerMetaTag([
    'name' => 'description',
    'content' => Html::encode($model->description),
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => Html::encode($model->keywords)
]);
?>
<section class="blog">
    <div class="blog-header"></div>
    <div class="inner">
        <aside class="side-left"></aside>
        <aside class="side-right">
            <?php if(isset($model->boxes['banner'])):?>
            <div class="b-module">
                <?= Html::img('@boxes/' . $model->boxes['banner']['image'])?>
            </div>
            <?php endif;?>
            <div class="b-module rss">
                <?= Yii::$app->session->hasFlash('message') ? Html::tag('legend', Yii::$app->session->getFlash('message'), ['class' => 'flash_message']) : ''?>
                <h3>
                    Подписывайтесь на наш блог
                </h3>
                <?= $this->render('/partials/_subscribe_form', ['model' => new Subscribers()])?>
            </div>
            <div class="b-module rss screen">
                <h3>
                    Популярные тэги
                </h3>
            </div>
        </aside>
        <div class="b-content">
        <?php if ($model = Blog::getAllBlogs()):?>
            <?php foreach ($model as $blog): ?>
                <article>
                    <h2>
                        <?= Html::a($blog['name'], Url::to(['blog/view', 'alias' => $blog['alias']]))?>
                    </h2>
                    <div class="date">
                        <?= Yii::$app->formatter->asRelativeTime($blog['created_at'])?>
                    </div>
                    <?php if($blog['image']):?>
                        <div class="media">
                            <?= Html::img('@blog/' . $blog['image'], ['alt' => '', 'title' => ''])?>
                        </div>
                    <?php endif;?>
                    <?= StringHelper::truncate(str_replace('[image]','', strip_tags($blog['text'],'<p>')), 700)?>
                </article>
            <?php endforeach; ?>
        <?php endif; ?>
        </div>
    </div>
</section>

frontend/views/site/buy.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Pages */
$this->title = Html::encode($model->title);
$this->registerMetaTag([
    'name' => 'description',
    'content' => Html::encode($model->description),
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => Html::encode($model->keywords)
]);
?>
<section class="map">
    <div class="map-header"></div>
    <div class="map-content">
        <div class="inner">
            <h2>
                Найдите ближайший магазин с нашей продукцией
            </h2>
            <h3>
                Введите в поиске название города
            </h3>
            <form id="city__search">
                <input type="text" id="suggest" name="city" placeholder="Город"><input type="submit" value="">
            </form>
        </div>
        <div class="b-map">
            <div id="myMap"></div>
        </div>
        <!--<div class="gallerey-magazine">
            <div class="inner">
                <h2>
                    Галлерея продукции на полке
                </h2>
            </div>
            <?//php if($images = \common\models\GeographyImages::getList()):
                //$count = 1;?>
            <ul>
                <li>
                    <?//php foreach($images as $i):?>
                        <?//php if (($count % 2) == 1 && $count > 1) echo '<li></li>';
                            //echo Html::a(Html::img('@geography/'.$i['basename'] . '.' . $i['ext']), '#');
                        //$count++;?>
                    <?//php endforeach;?>
                </li>
            </ul>
            <?//php endif;?>
        </div>
        <div class="inner add-mag">
            <a class="btn green fancybox" href="#search-shop">ДОБАВИТЬ МАГАЗИН</a>
            <p>
                или свяжитесь с нашим <a href="#">отделом продаж</a>
            </p>
        </div>-->
    </div>
</section>
<?php $this->registerJsFile('https://api-maps.yandex.ru/2.1/?lang=ru_RU');?>
<?php $this->registerJsFile('js/_yandex_map.js',['depends'=>'yii\web\JqueryAsset']);?>

frontend/views/site/error.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $message string */
/* @var $exception Exception */
$this->title = 'К сожалению запрашиваемая Вами страница не найдена.';

$this->title = Html::encode($this->title);
$this->registerMetaTag([
    'name' => 'description',
    'content' => Html::encode($this->title),
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => Html::encode($this->title)
]);
?>
<section class="page-404 b-top-section">
    <div class="title">
        404
    </div>
    <div class="sub-title">
        <?= nl2br(Html::encode($message)) ?>
    </div>
    <div class="btns">
        <?= Html::a('на главную', Yii::$app->homeUrl,['class' => 'btn'])?>
    </div>
</section>

frontend/views/site/page.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use common\models\Workers;

/* @var $this yii\web\View */
/* @var $model common\models\Pages */
$this->title = Html::encode($model->title);
$this->registerMetaTag([
    'name' => 'description',
    'content' => Html::encode($model->description),
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => Html::encode($model->keywords)
]);
?>
<section class="blog">
    <div class="blog-header"></div>
    <div class="inner">
        <aside class="side-left"></aside>
        <aside class="side-right"></aside>
        <div class="b-content">
            <article>
                <h2>
                    <?= $model->name?>
                </h2>
            </article>
        </div>
    </div>
</section>

frontend/views/site/price_old.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\Catalog;
use common\models\CatalogItems;
use common\models\PricesValues;

/* @var $this yii\web\View */
/* @var $model common\models\Pages */
$this->title = Html::encode($model->title);
$this->registerMetaTag([
    'name' => 'description',
    'content' => Html::encode($model->description),
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => Html::encode($model->keywords)
]);
?>
<section class="price">
    <div class="inner">
        <h1>
            <span class="fright">Ваш менеджер: <i><?= strip_tags(\common\models\Boxes::getBox('header_phone'))?></i></span><?= $model['name']?>
        </h1>
        <table>
            <tbody>
            <tr class="head">
                <td class="col-img"></td>
                <td class="col-name">
                    Наименование
                </td>
                <td class="col-massa">
                    Масса гр.
                </td>
                <td class="col-up">
                    В упаковке
                </td>
                <td class="col-count">
                    Кол-во
                </td>
                <td class="col-price">
                    Цена <img src="/images/rub.png" alt="">
                </td>
                <td class="col-sum">
                    Сумма <img src="/images/rub.png" alt="">
                </td>
            </tr>

            <?php if ($catalogs = Catalog::find()->select('id,name')->publish()->orderBy('pos ASC')->asArray()->all()):?>
                <?php foreach($catalogs as $catalog):?>
                    <tr class="pos-title">
                        <td colspan="7">
                            <?= $catalog['name']?>
                        </td>
                    </tr>
                    <?php if ($items = CatalogItems::loadItemsOneImage($catalog['id'])): $step = 1;?>
                        <?php foreach($items as $item):?>
                            <tr class="product<?= $step == 1 ? ' col-with-img' : ''?>">
                                <?php $path_preview = isset($item['galleryImages'][0]['basename']) ? $item['galleryImages'][0]['basename'].'_thumb.'.$item['galleryImages'][0]['ext'] : '';?>
                                <?php if($step == 1):?>
                                    <td class="col-img" rowspan="<?= count($items)?>">
                                        <div class="b-img">
                                            <?= Html::img('@gallery/'.$path_preview)?>
                                        </div>
                                    </td>
                                <?php endif;?>
                                <td class="col-name">
                                    <div class="product-name" data-img="<?= Yii::getAlias('@gallery').'/'.$path_preview?>">
                                        <?= $item['name']?>
                                    </div>
                                </td>
                                <td class="col-massa">
                                    <?= ($weight = \common\models\Weight::getValueById($item['weight_id'])) ? $weight : '---'?>
                                </td>
                                <td class="col-up">
                                    <span><?= ($in_package = $item['in_package']) ? $in_package : '---'?></span>
                                </td>
                                <td class="col-count">
                                    <div class="price-count-inp">
                                        <a class="minus fleft"></a><a class="plus fright"></a><input class="count" type="text" name="" value="0">
                                    </div>
                                </td>
                                <td class="col-price">
                                    <?= PricesValues::getPriceValue($model->price_id, $item['id'])?>
                                </td>
                                <td class="col-sum">
                                    0
                                </td>
                            </tr>
                        <?php $step++; endforeach;?>
                    <?php endif;?>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
        </table>
        <form>
            <table>
                <tbody>
                <tr class="itogo">
                    <td colspan="5">
                        Итого:
                    </td>
                    <td class="count-sum">
                        0
                    </td>
                    <td class="sum-rub" colspan="2">
                        <span>0 </span> <img src="/images/rub.png" alt="">
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="price-bottom">
                <div class="price-loginfo">
                    <b>Логистическая информация: </b>1 пак = 12 SKU;  Размер: 57 х 41 х 16 см;<br>Брутто: 3,5 кг: 1 пал (120 x 80 x 170) = 40 паков;  ШК = 4665272421487
                </div>
                <div class="price-checks">
                    <div class="form-item">
                        <label><input type="checkbox" name="reklama" id="reklama" checked><span>Выслать рекламные материалы</span></label>
                    </div>
                    <div class="form-item">
                        <label><input type="checkbox" name="obrazci" id="obrazci"><span>Выслать образцы</span></label>
                    </div>
                </div>
                <div class="price-submit">
                    <a href="#order" class="form-submit fancybox">Оформить</a>
                </div>
            </div>
            <div class="price-hidden">
                <table></table>
            </div>
        </form>
    </div>
</section>

<div id="order" class="popup">
    <div class="popup-head"></div>
    <div class="popup-content">
        <div class="title">
            ЗАПОЛНИТЕ ЗАЯВКУ
        </div>
        <?php $order = new \common\models\OrderSend();
        $form = ActiveForm::begin([
            'action' => \yii\helpers\Url::toRoute('site/send-order'),
            'id' => 'price_form'
        ])?>
        <?= Html::input('hidden', 'email_to', \common\models\Prices::getEmail($model->price_id), ['class' => 'email_to'])?>
        <?= $form->field($order, 'name')->textInput(['placeholder' => 'Введите имя', 'class' => 'name'])->label(false)->error(false)?>
        <?= $form->field($order, 'email')->textInput(['placeholder' => 'Электронный адрес', 'class' => 'email'])->label(false)->error(false)?>
        <?= Html::submitInput('ОТПРАВИТЬ', ['class' => 'btn border'])?>
        <?php ActiveForm::end(); ?>
    </div>
</div>